include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    prefer_relative_imports: true
    directives_ordering: true
    sort_child_properties_last: true
    always_use_package_imports: false
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    curly_braces_in_flow_control_structures: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_void_to_null: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    invalid_assignment: warning
    missing_return: error
    todo: ignore
